services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: coffee-shop-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-coffee_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-coffee_pass}
      POSTGRES_DB: ${POSTGRES_DB:-coffee_shop}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-coffee_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coffee-network

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: coffee-shop-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coffee-network

  # FastAPI Application
  api:
    build: .
    container_name: coffee-shop-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-coffee_user}:${POSTGRES_PASSWORD:-coffee_pass}@db:5432/${POSTGRES_DB:-coffee_shop}
      SECRET_KEY: ${SECRET_KEY}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DEBUG: ${DEBUG:-true}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - coffee-network

  # Celery Worker
  celery-worker:
    build: .
    container_name: coffee-shop-celery-worker
    command: celery -A app.core.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-coffee_user}:${POSTGRES_PASSWORD:-coffee_pass}@db:5432/${POSTGRES_DB:-coffee_shop}
      SECRET_KEY: ${SECRET_KEY}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - coffee-network

  # Celery Beat Scheduler
  celery-beat:
    build: .
    container_name: coffee-shop-celery-beat
    command: celery -A app.core.celery_app beat --loglevel=info
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-coffee_user}:${POSTGRES_PASSWORD:-coffee_pass}@db:5432/${POSTGRES_DB:-coffee_shop}
      SECRET_KEY: ${SECRET_KEY}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - coffee-network

volumes:
  postgres_data:
  redis_data:

networks:
  coffee-network:
    driver: bridge
